# Generated by Django 2.2 on 2019-07-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaLengkap', models.CharField(max_length=30)),
                ('NoTelp', models.CharField(max_length=10)),
                ('NoHP', models.CharField(max_length=20)),
                ('Provinsi', models.CharField(max_length=30)),
                ('kota', models.CharField(max_length=30)),
                ('Alamat', models.TextField()),
                ('KodePos', models.TextField(max_length=10)),
                ('Email', models.TextField(max_length=20)),
            ],
        ),
    ]
